# Generated by Django 4.2.6 on 2023-11-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_likes_like_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
